# railway.toml
[build]
builder = "Nixpacks"

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app"

[nixpacks]
# Explicitly tell Nixpacks to only consider Python.
# This helps prevent detection of other languages like Node.js.
providers = ["python"]